language: ruby
rvm:
- 2.1
before_install:
- wget https://raw.githubusercontent.com/creationix/nvm/v0.33.2/nvm.sh -O ~/.nvm/nvm.sh
- source ~/.nvm/nvm.sh
- nvm install 6
- node --version
- npm install -g grunt-cli
install:
- bundle install --jobs=3 --retry=3
- npm install
- npm install -g httpsnippet
script:
- grunt build
branches:
  only:
  - master
deploy:
  provider: s3
  region: eu-west-1
  access_key_id: AKIAJYKCFAGJAAGE2MKQ
  secret_access_key:
    secure: Lyf5fNvgU1hZ8/20kP9Yzp+TYhpVlPukPVlPjexIhuawwBaJEkNEfhqgWmUWcLkhkdJm2TjWQ6geh+DciZ7M7u7ZThHkmRBILqu/r7QCANTsQLkDcj3kX+Rt/jK6ytlyZqzoq6yGoMZXrL50WjiXvOXbfwsi7L/t1OYioPM4MJWwT1uBKfBl2dxaTFLTTK8f5v5aK/AKJ1Zm7U2N0EUq88MCZirQ5GzIMA+LmNciIs518kBr3ZVMxM6cNe/Tn5NaaJFm0deXrfDBWoS/272uieZzjvmdUAfCeZskH1/40g6Y6DSDeJ3gHfZwCAYqYxiS59z58yJODstv+VZXvI+kYVsmSdIHfmE9nqMBFFcLBbPsuYU1gPDnBMKZflGzsSWOKtuaqSjtB4P/1bxzurNOPjeIcfuD6IWmczVHakGFbbp4+qG5VTu5wLgENWv2evdxI/Bz/99iEjClwhOftX72VZ208iaUoFHNjlBykgxSM0aDCKQExzKotoF3zLn1eLGjak2weW2fdmVGq5ZTcRCow3hoWqgidewjN5G9Hwi6qh/bRvKDqEX4rVpb/3UElc63/ZALxhvi5bFJue4/nwbqmNLzG79yYjPJcomrJEmqZLeUAikpkjH9oYhaw0+HUwTV02Z+2DgVNxFNWmW9xtRm4yCwG+dQmTlxhi9TSQDZuc4=
  bucket: developers-test.hubofallthings.com
  local-dir: dist
  acl: public_read
  on:
    repo: Hub-of-all-Things/open-source-developer-portal
  skip_cleanup: true
