language: ruby
rvm:
  - 2.1
before_install:
  - git config --global user.email "travis@example.com"
  - git config --global user.name "Travis CI"
  - openssl aes-256-cbc -K $encrypted_634f038e8b4c_key -iv $encrypted_634f038e8b4c_iv -in travis_hat_dev_portal.enc -out travis_hat_dev_portal -d
  - chmod 600 travis_hat_dev_portal
  - eval `ssh-agent -s`
  - ssh-add travis_hat_dev_portal
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.33.2/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 6 # for Node v6
  - node --version
  - npm install -g grunt-cli
install:
  - bundle install --jobs=3 --retry=3
  - npm install
  - npm install -g httpsnippet
script:
  - grunt deploy
branches:
  only:
    - master
