language: ruby
rvm:
- 2.1
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_634f038e8b4c_key -iv $encrypted_634f038e8b4c_iv
  -in travis_hat_dev_portal.enc -out travis_hat_dev_portal -d
- chmod 600 travis_hat_dev_portal
- eval `ssh-agent -s`
- ssh-add travis_hat_dev_portal
- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
- sudo apt-get install -y nodejs
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install 6
- sudo npm install -g grunt-cli
install:
- bundle install --jobs=3 --retry=3
- sudo npm install
- sudo npm install --global httpsnippet
- git config --global user.email "travis@example.com"
- git config --global user.name "Travis CI"
script:
- grunt deploy
branches:
  only:
  - master
