language: ruby
rvm:
- 2.1
before_install:
- wget https://raw.githubusercontent.com/creationix/nvm/v0.33.2/nvm.sh -O ~/.nvm/nvm.sh
- source ~/.nvm/nvm.sh
- nvm install 6
- node --version
- npm install -g grunt-cli
install:
- bundle install --jobs=3 --retry=3
- npm install
- npm install -g httpsnippet
script:
- grunt build
branches:
  only:
  - master
deploy:
  provider: s3
  region: eu-west-1
  access_key_id: AKIAJYKCFAGJAAGE2MKQ
  secret_access_key:
    secure: IanH+0t5sjCSX7PcXPckluSlJ3AlSBffbUekDMnmt8U7FrQjSti8qRBMtzw/bKAEwrE2GXwIyI6oJJpVoli1MqRxZZtz7l0nxZo+87uH9fH7zbmkcOeHxUJ2+KHqy/YaivxIbVXJuNvY41jFTyP5PWd5ATVpF9yyqS7baToeDfBZOcV03Y9q+HS6EjI4UOlsXpt4Bru8R06Zx+5g2aRJOmi0WEHC0VPAKsWsG1HtTcEBcwiO/umhJr75wJb40xlhAOV7jCtcxj2H42E1Dltw35gj2VhpZMdyoAEXThVl+tF9/FpIFTGEk1bS/HiAQhapSPwIHStDy7Uzxg0/jFTEAcmmNDd0OYQ7ovskuUeXjfKF8Wd1h12V8QkeJaQbmb40yHv5XVAaZNA2lPQ9nOhOAoO/M/4YHCuk53iypXO5uw6BZ8VylkSPaiSmPLfjXua2LXvK9hN0jcugCEuMQgFRfXk4qe81/CR6wfoSN+b/y0otfyza1SfjTiQomNu5trk2J3nKeNWdnWPwpzsSwCRzzMamLMfueBjTweh0mEyjqsxviBnFtk4WKQa99vnffUIfoPNJ+h7wdUC1DswhTYmjo8uF8k9Lvr0mzFyYXtukvY1mb09w9bUPJjsTp9zQOlC4/GaCg3r8Sk/s2uI9SRb63DexNYS2EVnI4tScWpGe72s=
  bucket: developers.hubofallthings.com
  local-dir: dist
  acl: public_read
  on:
    repo: Hub-of-all-Things/open-source-developer-portal
  skip_cleanup: true
